# Generated by Django 5.1.7 on 2025-03-30 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agency_loginhistory_useractivitylog_and_more'),
        ('properties', '0003_property_featured_propertyimage_processing_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalcontract',
            options={'verbose_name': 'Rental Contract', 'verbose_name_plural': 'Rental Contracts'},
        ),
        migrations.AlterModelOptions(
            name='salecontract',
            options={'verbose_name': 'Sale Contract', 'verbose_name_plural': 'Sale Contracts'},
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='administration_fee',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='appointment_fee',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='commitment_fee',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='closing_costs',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_agency',
            field=models.ForeignKey(blank=True, help_text='Agency that listed this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_properties', to='core.agency', verbose_name='Listing Agency'),
        ),
        migrations.AddField(
            model_name='property',
            name='viewing_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fee required to view this property', max_digits=10, verbose_name='Viewing Fee'),
        ),
        migrations.AddField(
            model_name='salecontract',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='salecontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('viewing', 'Property Viewing Access'), ('rental', 'Rental Processing'), ('purchase', 'Purchase Processing')], max_length=20, verbose_name='Service Type')),
                ('valid_until', models.DateTimeField(help_text='Subscription expiration date', verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='properties.property', verbose_name='Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service Subscription',
                'verbose_name_plural': 'Service Subscriptions',
                'unique_together': {('user', 'property', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('admin', 'Administration Fee'), ('processing', 'Processing Fee'), ('commitment', 'Commitment Fee'), ('viewing', 'Viewing Fee'), ('rent', 'Rent Payment'), ('purchase', 'Purchase Payment')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('payment_id', models.CharField(help_text='Unique identifier from payment processor', max_length=255, unique=True, verbose_name='Payment ID')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='Property')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.servicesubscription', verbose_name='Service Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
