# Generated by Django 5.1.7 on 2025-04-01 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_rentalcontract_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('place_type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('park', 'Park'), ('shopping', 'Shopping Center'), ('transport', 'Public Transport'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Place of Interest',
                'verbose_name_plural': 'Places of Interest',
            },
        ),
        migrations.CreateModel(
            name='PropertyPlaceOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=1, help_text='Distance from the property', max_digits=5, verbose_name='Distance (miles)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.placeofinterest', verbose_name='Place of Interest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_places', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Place of Interest',
                'verbose_name_plural': 'Property Places of Interest',
                'unique_together': {('property', 'place')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='places_of_interest',
            field=models.ManyToManyField(help_text='Significant locations near this property', related_name='properties', through='properties.PropertyPlaceOfInterest', to='properties.placeofinterest', verbose_name='Nearby Places of Interest'),
        ),
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='properties.property', verbose_name='Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Property Interest',
                'verbose_name_plural': 'Property Interests',
                'unique_together': {('user', 'property')},
            },
        ),
    ]
