# Generated by Django 5.1.7 on 2025-04-03 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agency_options_alter_user_options_and_more'),
        ('properties', '0005_placeofinterest_propertyplaceofinterest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='propertyvideo',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('both', 'For Sale and Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_properties', to='core.agency'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='places_of_interest',
            field=models.ManyToManyField(related_name='properties', through='properties.PropertyPlaceOfInterest', to='properties.placeofinterest'),
        ),
        migrations.AlterField(
            model_name='property',
            name='viewing_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Viewing Fee'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyplaceofinterest',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Distance (miles)'),
        ),
        migrations.AlterField(
            model_name='propertyplaceofinterest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.placeofinterest'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video Thumbnail'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video_file',
            field=models.FileField(upload_to='property_videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salecontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salecontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_contracts', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.servicesubscription'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
