# Generated by Django 5.1.7 on 2025-04-06 13:38

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaynowIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('integration_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('integration_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('return_url', models.URLField()),
                ('result_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Paynow Integration',
                'verbose_name_plural': 'Paynow Integrations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Created', max_length=20)),
                ('paynow_payment_id', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('poll_url', models.URLField(blank=True, max_length=500)),
                ('error_message', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paynowintegration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'), models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx')],
            },
        ),
    ]
