# Generated by Django 5.1.7 on 2025-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paynowintegration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
