# Generated by Django 5.1.7 on 2025-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_url_paynowintegration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paynowintegration',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
