# Generated by Django 5.1.7 on 2025-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_buyer_phone_paynowintegration_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paynowintegration',
            name='integration_id',
            field=models.CharField(max_length=100),
        ),
    ]
