# Generated by Django 5.1.7 on 2025-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paynowintegration_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paynowintegration',
            name='sandbox_mode',
            field=models.BooleanField(default=True),
        ),
    ]
