# Generated by Django 5.1.7 on 2025-05-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_buyer_email_paynowintegration_sandbox_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='paynowintegration',
            name='sandbox_mode',
        ),
    ]
