# Generated by Django 5.1.7 on 2019-12-07 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_buyer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Receipt Number')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('payment_method_details', models.CharField(blank=True, max_length=100, verbose_name='Payment Method')),
                ('items_description', models.TextField(blank=True, verbose_name='Items/Services Description')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/pdfs/', verbose_name='Receipt PDF')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issued_at'],
            },
        ),
    ]
